[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar && waybar &'

[templates.discord]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/Vesktop/themes/matugen.css'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/matugen-themed'
post_hook = 'pkill dunst && dunst -conf ~/.config/dunst/matugen-themed &'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-template.rasi'
output_path = '~/.config/rofi/colors.rasi'
